<template>
  <div v-html="content"></div>
</template>

<script setup>

const content = `
  <div>
    <h1>Texte</h1>
  </div>
  <div>
    <p><strong>WIDER DIE VERBRAUCHTEN GESTEN</strong><strong><br /> 
      Nader Mashayekhi und seine Oper <em>Malakut</em><br /> 
      Erschienen in "Neue Zeitschrift für Musik", Nr. 6, 1997<br /> 
      Wider die verbrauchten Gesten</strong></p>
    <p>Die Gattung Oper übt eine ambivalente Anziehungskraft auf die jüngere Komponistengeneration aus. Gerade in Österreich, wo von seiten der Bundes- und Landestheater die Aufführungschancen für musikdramatische Werke durch mangelnde Innovationsbereitschaft, Ignoranz und geistige Trägheit nahezu gleich Null sind, macht sich der Trend bemerkbar, die Oper als ein artifizielles Understatement gegen das Establishment zu verstehen, als Akt der künstlerischen Selbstbehauptung und Eigendefinition. Da arbeitet beispielsweise ein Christian Ofenbauer fünf Jahre lang ohne öffentlichen Auftrag, ohne Subvention und ohne Aussicht, jemals das Produkt auf der Bühne realisiert zu sehen, an der musikalischen Umsetzung des Medea-Stoffes; da wagt der Third-Stream-Komponist und Jazzmusiker Franz Koglmann den Vorstoß in bislang neue Bühnen-Gefilde und projektiert die erste Cool-Jazz-Oper der Musikgeschichte, basierend auf französischen und amerikanischen Kultfilmen. Während die öffentlichen Häuser immer marktorientierter aufs Repertoire zurückgreifen und bestenfalls mit Berg oder Britten auf gesichertes Opernterrain setzen, konnte sich - zumindest in Wien - eine freie Opernszene etablieren, die der kulturellen Unterversorgung der Musikmetropole mit zeitgenössischen Opemwerken entgegenzuwirken sucht. Einer dieser Veranstalter, das "Wiener Operntheater" unter seinem Leiter Sven Hartberger, ist nun noch einen Schritt weiter gegangen: Neben internationaler Moderne (in den letzten Jahren: Ligeti, Penderecki, Birtwistle, Reimann, Boesmans, Adams) steht nun auch ein österreichischer Komponist auf dem Programm: Nader Mashayekhi mit der Uraufführung seiner Oper Malakut im Rahmen von "Wien Modern". Der 1958 in Teheran geborene Komponist lebt seit 1978 in Wien, studierte bei Roman Haubenstock-Ramati und ist trotz internationaler Beachtung in der Szene ein Außenseiter geblieben. Er ist einer von den Künstlern, denen das österreichische Kulturleben jede Menge Durchhaltevermögen abverlangt, um nicht...
      Christian Baier</p>
    <p><strong>Herbstliches Gespräch in Hawei*<br />
    </strong>I<strong>nterview, erschienen im Programmheft des Konzerts am 5. November 1997 im Festspielhaus St. Pölten<br />
    Heinz Rögl im Gespräch mit Nader Mashayekhi</strong></p>
    <p>FESTSPIELHAUS: Zu Mahlers Lied von der Erde hast du schon lange ein fasziniertes Verhältnis. Seit wann genau?</p>
    <p>MASHAYEKHI: Ich kam immer wieder darauf zurück und jedesmal natürlich auf andere Art und Weise. Mit siebzehn sah ich in Persien zum ersten Mal eine Fernsehaufzeichnung, ich glaube mit René Kollo und Christa Ludwig unter Bernstein. Ich war hingerissen, vor allem vom ersten, dritten, vierten und fünften Lied. Noch nicht vom zweiten und sechsten.<br />
      Es gab in Teheran nur ein Plattengeschäft, in dem man klassische Musik kaufen konnte. Dort wollte ich, noch vor meinem Erlebnis mit dem Lied von der Erde, etwas von Wagner kaufen, und da haben sie Musik von Mahler gespielt. Ich dachte, das mull ich unbedingt haben. So fing es an. Einige Mahler-Symphonien, nicht alle und auch nicht alle Sätze davon, haben mich seither berührt. Später, hier in Wien, interessierte mich wieder das Lied von der Erde, vor allem die beiden Sätze, die heute beim Konzert gespielt werden: Der Einsame im Herbst und Der Abschied.</p>
    <p>FESTSPIELHAUS: Das sind die beiden Lieder des Zyklus, die am meisten einen todessymbolischen Grundton anschlagen. Dann fällt auf, dab das Lied vom Einsamen im Herbst das am kammermusikalischsten instrumentierte Stück ist. Schon wie es beginnt, nur mit dieser Geigenlinie und dem Oboensolo, dann dessen Echo in der Flöte ...</p>
    <p>MASHAYEKHI: Es geht mir in erster Linie um die Stimmung dieser Lieder. Um dieses "Kälte spüren". Die Kälte, die Mahler in der "Normalität" verspürt. Und dann diese letzten siebzig Takte im Abschied, in denen sich fast nichts mehr bewegt. Dieses unendliche "Ewig, ewig..."</p>
    <p>FESTSPIELHAUS: In deiner Version singt eine Mezzosopranistin. Wie hast du sonst für Kammerensemble instrumentiert?</p>
    <p>MASHAYEKHI: Die Streicher sind Solistisch besetzt, ansonsten versuche ich, dieselben Instrumente zu verwenden wie Mahler, bloß klein besetzt. Ich habe nur zwei Hörner, eine Posaune und so weiter. Um eine chorische Wirkung zu erzielen, spielen am Beginn von "Der Einsame im Herbst" alle höheren Streichinstrumente die Linie der ersten Violine. Ich habe auch die Horngruppe mit einem Fagott "gefüllt" oder den Kontrabaß die Rolle des Kontrafagotts übernehmen lassen. Die Celesta kommt nur dort vor, wo auch Mahler sie einsetzt. Auf die Idee, ein Harmonium einzusetzen, wie Schönberg es in seiner Kammermusikfassung tat, käme ich nie.</p>
    <p>FESTSPIELHAUS: Welche Position nimmt nun deine eigene Komposition<em>3 + eine Nacht</em>für 101 Becken ein?</p>
    <p>MASHAYEKHI: Nachdem ich nur zwei Lieder Mahlers verwende, war meine ursprüngliche Idee, sozusagen eine "Umhüllung" zu schaffen. Die einzelnen Sätze, die ich "Pforten" nenne, nehmen nun die Position der fehlenden Lieder ein.<br />
      Das Konzert beginnt mit einer Introduktion, einer Solo-Improvisation einer Persischen Flöte, die dann in die "1. Pforte" der Musik für 101 Becken übergeht. Diese Musik ist kalligraphisch notiert und wird von vier bunt gekleideten Spielern ausgeführt. Jeder bedient je 25 (einer 26). Die erste "Pforte" dauert 7 Minuten und 30 Sekunden, das entspricht der Dauer des "Trinklieds vom Jammer der Erde". Zweite, dritte und vierte "Pforte" folgen dann auf das Lied "Der Einsame im Herbst" und ersetzen die Lieder "Von der Jugend", "Von der Schönheit" und "Der Trunkene im Frühling". Dann gibt es eine Pause. Den zweiten Teil leitet wieder die Persische Flöte ein, und es folgt "Der Abschied". Nach dem "Ewig ..." kann man keine andere Musik mehr hören! Die beiden Teile vor und nach der Pause ergeben jeweils achtunddreißig Minuten Musik, was der Gesamtspieldauer des Liedes von der Erde in etwa entspricht.</p>
    <p>FESTSPIELHAUS: Bunt gekleidete Musikanten, die den lebenssymbolischen Gestus der anderen Lieder, zumal der symphonischen, fanfarenartigen Einleitung des ersten versinnbildlichen?</p>
    <p>MASHAYEKHI: Ja, vielleicht ... Genau! Die neu komponierte Musik ist der Ersatz für die Lieder, die mich in meiner Jugend fasziniert haben. Was ich mache, ist eine "Übermalung" meiner eigenen Jugend.</p>
    <p>FESTSPIELHAUS: Die Persische Flöte (statt der Bethgeschen "chinesischen Flöte" ist ein sehr archetypisches Instrument.</p>
    <p>MASHAYEKHI: Sie ist auch schwierig zu erlernen! Man braucht sechs Monaten, um vielleicht einen Ton hervorbringen zu können, und der Resonanzraum der Mundhöhle ist für die Tonerzeugung maßgeblich. Man kann verschiedene Klangfarben erzeugen. An die vorderen Zähne angesetzt, klingt sie wie gehaucht, und auch Flageolettöne sind möglich.</p>
    <p>FESTSPIELHAUS: Wie stellst du dich zu den Versuchen, Mahler eingeschlossen, orientalische Musik und Exotismen in der westlichen Musik zu verwenden? Oder persische Gedichte in anderen Sprachen nachzudichten?</p>
    <p>MASHAYEKHI: Das ist fast unmöglich und bei Mahler nicht direkt geschehen. Es ist vor allem Musik des Fin de Siècle, aber nicht nur, sondern mehr als das. Bei Übersetzungen klassischer Literatur und Poesie aus dem Persischen, die im 19. Jahrhundert, soviel ich weiß, zuerst ins Französische erfolgten, kann ja oft das Wesentliche - wie zum Beispiel der Rhythmus eines "Gedankentanzes" bei Rumi, der oft bedeutsamer als die verwendeten Wörter ist - nicht übersetzt werden. In der Übersetzung wird eine andere Realität geschaffen. Die Wörter, selbst das Wort "Vogel", haben in der persischen Poesie oft eine ganz andere Bedeutung als im Westen. Was die Musik betrifft, glaube ich persönlich, dab es nicht gut ist, heutige Instrumente mit alten persischen, die sich anders entwickelt haben und auch viel leiser sind, zu mischen. Das Tar (Langhalslaute) oder die Ney (Persische Flöte) wird von einer modernen Geige mühelos zugedeckt. Was ich allerdings demnächst (mit dem Klangforum Wien) ausprobieren möchte, ist die Kombination persischer Instrumente mit Barockinstrumenten wie Clavecin, Clavichord oder Traversflöte.</p>
    <p>FESTSPIELHAUS: Du bezeichnest die Sätze deiner Musik als "Pforten", wie auch die Szenen in deiner Oper<em>Malakut</em>.</p>
    <p>MASHAYEKHI: Das ist eine Tradition im Persischen. Das Wort "Bab", aus den ersten beiden Buchstaben des Alphabets gebildet (für "Pforte, Tür"), bedeutet auch "Abhandlung über etwas, über etwas sprechen". Für mich bedeutet das "Anfang".</p>
    <p>FESTSPIELHAUS: Die verschiedenen Möglichkeiten, ein Stück anzufangen, haben in deinem Komponieren eine große Bedeutung.</p>
    <p>MASHAYEKHI: Auch die vier Spieler der Becken, die aus ein und derselben Partitur spielen, beginnen jeweils an anderen Stellen. Die "Pforten" 1 und 3 sowie 2 und 4 stehen in Verhältnis zueinander und sind immer in einen lyrischen und einen schnellen Abschnitt zweigeteilt.</p>
    <p>FESTSPIELHAUS: In der Disposition deiner Musik, aber auch in der Ablaufdramaturgie der von dir "komponierten" Konzerte spielt Zeitdauer eine wichtige Rolle.</p>
    <p>MASHAYEKHI: Es geht darum, in eine andere Zeitebene, als die Realität sie darstellt, einzutauchen. Es gibt mehrere Zeiten, und ich erfahre das am eigenen Leib immer mehr, je älter ich werde. Auch seit ich einen Sohn habe, mit dem ich mich viel beschäftige. Das Erinnern an vergangene Lebensabschnitte wird mir immer wichtiger. Das Erleben "eines Prozesses in mehreren Blicken", überlagert durch je individuelle Erinnerung, spielt auch die zentrale Rolle in meiner Oper.</p>
    <p>FESTSPIELHAUS: Hast du Mahlers Musik eigentlich bewußt auf ein kleines Ensemble übertragen? Würdest du auch gerne für große Orchester komponieren?</p>
    <p>MASHAYEKHI: Ich bin wie ein Pfeil in einem gespannten Bogen, was das Interesse an Arbeit mit großen Besetzungen, auch das Dirigieren, betrifft. Routine-Musiker sagen allerdings oft bei einer Stelle: "Das geht nicht". Sie verstehen auch manchmal nicht, dab eine bestimmte Spielweise nicht nur Verzierung, sondern struktureller Bestandteil einer Komposition ist. Das Arbeiten mit dem Ensemble 2001 ist allein schon deswegen so schön, weil sich alle unendlich viel Zeit zum Arbeiten und Diskutieren nehmen. Und man kann sogar bei der Generalprobe noch etwas verändern.</p>
    <p>*Nader Mashayekhi wohnte zum Zeitpunkt des Gesprächs in Hadersdorf-Weidlingau an den Gestaden der Westbahn.</p>
  </div>
`
</script>
